### ISSUE TITLE
Unable to extract partition id from Alarm.com

### ISSUE THREAD

**Issue by ade5hmukh** [uvjustin/alarmdotcomajax#10]
Hello Folks, 
I am running Home Assistant 0.110.2 (docker instance on Ubuntu Server). 
I have the following in configuration.yaml:
alarm_control_panel:
  - platform: alarmdotcomajax
    name: Alarm.com
    username: !secret
    password: !secret

I get the following log on home-assistant:
2020-05-25 18:33:04 ERROR (MainThread) [pyalarmdotcomajax.pyalarmdotcomajax] Unable to extract partition id from Alarm.com
2020-05-25 18:33:04 ERROR (MainThread) [homeassistant.components.alarm_control_panel] Error while setting up alarmdotcomajax platform for alarm_control_panel
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/alarmdotcomajax/alarm_control_panel.py", line 78, in async_setup_platform
    await alarmdotcom.async_login()
  File "/config/custom_components/alarmdotcomajax/alarm_control_panel.py", line 124, in async_login
    await self._alarm.async_login()
  File "/usr/local/lib/python3.7/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py", line 149, in async_login
    self._partitionid = json["data"]["relationships"]["partitions"]["data"][0][
IndexError: list index out of range

Please pardon me if this is not the right mode of raising issue with this module. 
Thanks

**Comment by uvjustin** [comment]
Interesting. I'm not aware of anyone else having this problem so it might be something on your end. I'm using 0.110.2 and there should be nothing with the new release which would cause this.
Was this integration working for you previously?
Check that the ADC login you are using proper permissions and that 2FA is not enabled for that login.

**Comment by ade5hmukh** [comment]
Was this integration working for you previously?
--Completely new to this integration and home-assistant. 
Check that the ADC login you are using proper permissions
-- ADC login has just username and password. No 2FA. Any specific permissions need to be set for API calls?
-- Is there anyway I can login via API and check if it's working? 

I don't know if this maybe a problem but --
I have another platform (manual) under alarm_control_panel which is for my wired security sensors integrated with konnected.io and it works fine.

**Comment by uvjustin** [comment]
The other platform shouldn't be an issue. There is a problem with scraping the page when using your login.
For permissions, it should work with either "Full Control", "Master Control", or "Custom" with remote arming checked. Are you able to see everything in the system from the home page at https://www.alarm.com/web/system/home ?

**Comment by uvjustin** [comment]
It just occurred to me you might not be using secrets properly. Try entering the username and password without secrets first to troubleshoot.
For the secrets syntax see https://www.home-assistant.io/docs/configuration/secrets/

**Comment by ade5hmukh** [comment]
Oh I'm not using secrets and that was just for demonstration purposes only. I am putting username and password in plain-text. 
I just created new user on alarm.com with Master control permissions and changed HA config with the username/password but the same error. 
2020-05-26 10:38:44 ERROR (MainThread) [pyalarmdotcomajax.pyalarmdotcomajax] Unable to extract partition id from Alarm.com

I am able to login as any user and see everything in the system from the home page at https://www.alarm.com/web/system/home. 

Can this be a problem -->
This panel system is installed by third party who support/warrants our home monitoring devices. Do I need to get any permissions from them? I don't think so because we didn't pay for monitoring services and are on our own. 

I appreciate your assistance on this issue. Thanks!

**Comment by uvjustin** [comment]
I don't think that that should be an issue as long as you can access the web portal, but I'm not familiar with all the ADC setups.
Unfortunately I can't help troubleshoot more without getting a temporary login to see where the scraping is breaking down. Would you be willing to send me one?

**Comment by ade5hmukh** [comment]
Sure. Can you let me know what permissions would you like on temporary login and your email address to send credentials. 
Thanks again for your help.

**Comment by uvjustin** [comment]
"Custom" with remote arming checked is fine. Can send it to me at 46082645+uvjustin@users.noreply.github.com
