### ISSUE TITLE
Question: Is there a way to control Z-Wave devices?

### ISSUE THREAD

**Issue by dpiper01** [uvjustin/alarmdotcomajax#13]
I’ve set up all the doors and motion sensors in Home Assistant but now my question is, can I connect my Z-Wave door lock to Home Assistant? 

I have the lock connected into my Alarm.com system.

Thanks a ton!

**Comment by uvjustin** [comment]
Sorry, this integration doesn't deal with the Z-wave functionality of Alarm.com.
There are other Z-wave hubs you can use with Home Assistant which will have more functionality/interoperability than the Alarm.com hub does (except you won't have the LTE connectivity which may be important to you).
See https://www.home-assistant.io/docs/z-wave/controllers/
