### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by cjeffcoat80** [uvjustin/alarmdotcomajax#14]
Hi,
 Im kinda new at HA. I have recently went from a Honeywell alarm panel to an Alarm.com panel. It is great and all but I can not seem to get it integrated into HA.... Any ideas. I am running HA version 0.114.3

**Comment by uvjustin** [comment]
The module should be downloaded from PyPI automatically by HA after HA loads the custom component. It's possible that the PyPI download failed for some reason, but it should have tried again on a subsequent HA reboot.
Are you still having this issue?

**Comment by coltondick** [comment]
I too am experiencing the same issue. 

> Platform error alarm_control_panel.alarmdotcomajax - No module named 'pyalarmdotcomajax'
> 8:07:29 AM – Home Assistant (ERROR)

I have resolved this however by installing the dependencies from manifest.json manually. 

`
pip install beautifulsoup4 pyalarmdotcomajax==0.1.2`

**Comment by uvjustin** [comment]
@aechelon Any idea why this would be happening?

**Comment by cjeffcoat80** [comment]
My issue has been resolved. But any idea why I have to put the code in to arm and disarm the alarm? Any way to automate it or have it automatically disarm and arm without typing the code in? I have the code in the configuration.yaml but it still requires me to input it manually.

**Comment by uvjustin** [comment]
The code you specify in configuration.yaml is actually there to force you to enter a code to arm/disarm through HA - it doesn't have to be related to the code on your alarm system. If you don't want to have to enter a code to arm/disarm, remove the code from your configuration.yaml.

**Comment by cjeffcoat80** [comment]
Perfect. I'll try that right now.

**Comment by cjeffcoat80** [comment]
any way to get it to disarm or is arm away and arm home all it is able to do?

**Comment by cjeffcoat80** [comment]
nevermind. dumb question. I figured it out.

**Comment by cjeffcoat80** [comment]
Thank you for taking the time out and giving me a hand. It is much appreciated

**Comment by uvjustin** [comment]
No worries, glad you were able to get it set up.
