### ISSUE TITLE
 Error executing Arm+Stay, logging in and trying again

### ISSUE THREAD

**Issue by roo-punch** [uvjustin/alarmdotcomajax#15]
I've added this integration by inputting a custom repo link into HACS. I'm running hass.io. I added settings to the configuration.yaml as instructed. The alarm.com integration shows up. However, when I go to use it I get this error:

Error executing Arm+Stay, logging in and trying again...
3:02:40 PM – /usr/local/lib/python3.8/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py (ERROR) - message first occurred at 3:02:36 PM and shows up 7 times

Any suggestions?

**Comment by uvjustin** [comment]
Do you have an Alarm.com package which includes security system support? Ie can you arm/disarm your system through the web page or mobile app?

**Comment by roo-punch** [comment]
Thanks for the response (and the project). Yep. I actually had notifications turned on for online logins and so I got about 800 emails after adding the integration for new logins. So it was definitely logging in correctly.

**Comment by uvjustin** [comment]
Check that the ADC login you are using has enough permissions to arm/disarm the system.

**Comment by roo-punch** [comment]
It is the master account. I've checked to make sure there is no 2FA, it can successfully arm/disarm, etc.

**Comment by uvjustin** [comment]
Interesting. Can you set the logging to debug and share what debug message it gives along with the error message?

**Comment by roo-punch** [comment]
This is what it came up with. Looks like a 422 response?

[alarmdotcomlogs.txt](https://github.com/uvjustin/alarmdotcomajax/files/5159864/alarmdotcomlogs.txt)

**Comment by uvjustin** [comment]
I'm not sure why the 422 is coming back - it could be an issue with grabbing the partition information, or it may be a result of rate limiting now (From your logs it looks like the requests you've sent are looping back, sending nonstop logins and arm commands. This may cause some kind of exception on the ADC side. I would recommend restarting HA and letting it cool off a bit. Does your arming from the app still work right now?)

**Comment by roo-punch** [comment]
That definitely sounds plausible, although not sure why it's getting that in the first place? I've disabled the integration again. The app is currently working fine.

**Comment by uvjustin** [comment]
Yes, I'm not sure either. Do you know if you have multiple partitions set up?
Would it be possible to make a temporary login for me to help troubleshoot?

**Comment by aechelon** [comment]
I've been thinking that it might be worthwhile to add a python script to help test the component independently from HA.  
@roo-punch, out of curiosity, who's your alarm.com provider?

**Comment by roo-punch** [comment]
@uvjustin Yes, how should I send it to you? I don't believe there are multiple partitions. @aechelon It is Brinks.

**Comment by aechelon** [comment]
Weird.  I'm also with Brinks and I can confirm that Arm+Stay works fine.

**Comment by roo-punch** [comment]
So I decided to try it with the new user I created and still no dice. Then I removed the optional parameters and bingo, it's working. It is working fine with 'code', but doesn't like 'force_bypass', 'no_entry_delay' or 'silent_arming'

**Comment by silentcossack** [comment]
Hey folks, so I just wanted to chime in that I'm seeing the exact same issue. Getting 422 code back, looping like mad after that. Commenting out the three options for bypass, delay and silent fixes the issue. Clearly something in the format of some of those options is not being like by alarm.com

**Comment by aechelon** [comment]
@silentcossack is this something that it started happening recently for an existing configuration?
Can you test setting silent_arming by itself to "true"?

**Comment by roo-punch** [comment]
@aechelon Tested, still seeing the same results. Overall I'm pleased to get it working though, I can live without those parameters. It could be to the benefit of everyone to throw some kind of error, rather than hammering the site. Would hate to see a captcha or something.

**Comment by silentcossack** [comment]
Ok, tested by putting the options back one by one and all work except one. Setting force_bypass to true breaks it. Hope this helps.

**Comment by uvjustin** [comment]
Good information, thanks for the feedback.
One thing to note - at least on my portal, some of those 3 parameters are not compatible with each other. For example, setting night arming to true greys out the away button. Setting no entry delay and night arming will not allow any arming at all.
I usually arm using force_bypass only, and I noticed that the command that gets sent only sends the force_bypass as true and just omits the other parameters instead of sending them as false. I'll make a change that doesn't send parameters when they are false. I'll also make a change to the library to keep it from retrying when it gets a 422.
@aechelon What kind of script do you suggest? Should it be in the pypi library or in this repo?

**Comment by jhbeskow** [comment]
Just commenting to follow this.  I have the same issue.  Setting all 3 to false is the only way I have gotten it to work so far.

**Comment by jhbeskow** [comment]
Quick correction.  no_entry_delay works as expected.  This configuration works, but if I change either of the false values to true, it stops working:

alarm_control_panel:
  - platform: alarmdotcomajax
    username: !secret alarm_username
    password: !secret alarm_password
    #code: !secret alarm_code
    force_bypass: "false"
    no_entry_delay: "home"
    silent_arming: "false"

**Comment by uvjustin** [comment]
Do the corresponding commands work on your ADC web portal?
For example, when you click both the no_entry_delay and force_bypass buttons, can you arm the system?
(silent_arming is called night_arming at least on my ADC web portal)

**Comment by jhbeskow** [comment]
I only have No Entry Delay available, which is weird because I can bypass at the panel.

**Comment by uvjustin** [comment]
Interesting. I guess the availability of options might be related to different ADC service providers or underlying alarm systems. Unfortunately it looks like we can't use certain options if they are not available in the web portal.

**Comment by uvjustin** [comment]
Haven't heard from the others in over a week, closing this issue for now.

**Comment by roo-punch** [comment]
That makes sense. I only have 'no entry delay' available in the portal as well.

**Comment by tcm0116** [comment]
I would like to note that I had this same issue with Brinks as well. You might want to consider adding some additional details to the documentation to indicate the limitations of the various services.

**Comment by uvjustin** [comment]
Ok, I will add a comment to the README
