### ISSUE TITLE
Sensors States are reversed

### ISSUE THREAD

**Issue by seanmccabe** [uvjustin/alarmdotcomajax#17]
Thanks for the integration, been using for a few days now, but seems to have come across the issue that the sensor states are in reverse.

I.e. Front Door is currently closed, but is showing open. This is the same for all sensors.

![image](https://user-images.githubusercontent.com/12243212/93030189-46f09580-f675-11ea-9e39-bf916d3e6317.png)

**Comment by uvjustin** [comment]
This integration just returns the sensor state as strings from what ADC returns. You can view what we return in the sensor_status attribute of your alarm panel entity. I suspect your problem with reversed states is probably from the mapping you are using in `value_template: `. See here: https://github.com/uvjustin/alarmdotcomajax#additional-features

**Comment by seanmccabe** [comment]
Map them all as per instruction with their state as they are. I.e. if front door closed, map as closed, and back door open as open.
However they don't through correctly, Often showing reversed, so open, when physically closed. Can flick between these states over hours when the door hasn't physically been opened/closed
