### ISSUE TITLE
No module named pyalarmdotcomajax

### ISSUE THREAD

**Issue by anatwick** [uvjustin/alarmdotcomajax#19]
When i follow all of the steps you have i get the following error:  "Platform error alarm_control_panel.alarmdotcomajax - No Module named 'pyalarmdotcomajax'"  i downloaded the files directly from this repository and in my custom components folder i have an alarmdotcomajax folder and within that folder i have the following three files: 1. _init_.py 2. alarm_control_panel.py 3. manifest.json

Any thoughts on how i could get this working?

**Comment by uvjustin** [comment]
HA should install the `pyalarmdotcomajax` module automatically as it's specified in the requirements section of the `manifest.json` file. For some reason a few people have said it doesn't install automatically for them, but you can work around this by installing it manually from inside your container/venv using the command `pip install pyalarmdotcomajax`.

**Comment by anatwick** [comment]
Stupid question but how do i do that? I am running an ubuntu VM in virtual box.  i entered in that command and it said pip is an unknown command

**Comment by anatwick** [comment]
I did find the pyalarmdotcomajax.py file and put it in the same custom components folder but no luck.

**Comment by uvjustin** [comment]
> 
> 
> Stupid question but how do i do that? I am running an ubuntu VM in virtual box. i entered in that command and it said pip is an unknown command

Where is HA running?
Try `pip3 install pyalarmdotcomajax`

**Comment by anatwick** [comment]
I guess I'm not following your question.  The server is on an ubuntu virutual machine running in virtual box.   I tried entering these commands from the command line interface within that and no such luck.

**Comment by anatwick** [comment]
I got it working!   I decided to go back in and play around with it and found the problem  i had Alexa Guard setup as an alarm for testing and that was causing issues apparently.  i disabled that and and now i can get the alarm.com panel to show up.  have to do some more tweaking as it doesnt seem to work but i have a feeling i'm over the biggest hurdle

**Comment by anatwick** [comment]
Its really strange actually... when i go into developer tools and look i can clearly see all of my sensors and there status perfectly. I can also see the malfunctions that i have (sensors need batteries) perfectly but when i arm the alarm using the interface in HA it doesnt actually do anything.  After clicking arm home it sits there and has a blue hue over arm home for maybe 5-10 seconds but never actually arms.  the status indicator in the upper right stays green the entire time and does not change anything on the panel. 

If i manually alarm the system on the panel it arms fine and on the developer tools the armed_home status is reflected instantly, and the panel on the lovelace ui shows red and armed home.  If i click to disarm from the panel and enter my code it disarms the alarm perfectly - on the actual panel as well as on the lovelace ui.        Even after disarming if i try to arm home it wont work. just sits there.

Any thoughts?  I've tried restarting the HA server with no real change at all.

**Comment by anatwick** [comment]
OK - Messed around with it all day and now it does seem to work Thank You for the help on this!
