### ISSUE TITLE
Enhancement Request: Enable no_entry_delay on only certain commands

### ISSUE THREAD

**Issue by masterhuh** [uvjustin/alarmdotcomajax#2]
It appears that the no_entry_delay works as an all or nothing in the current configuration.  Is it possible to cleanly make it so that it only occurs on "stay"?

**Comment by uvjustin** [comment]
Added the feature...give it a try

**Comment by uvjustin** [comment]
For the setting, I used the name "home" instead of "stay" as per HA convention (although in the pypi library I use the name "stay" instead of "home" as per the ADC convention). Hope it's not too confusing.

**Comment by masterhuh** [comment]
naming convention makes sense.  inserting "home" into the config unfortunately did not trigger "no_entry_delay" for when the system was set to 'stay/home' with the new build.

**Comment by uvjustin** [comment]
Fixed a typo...see if it works now

**Comment by masterhuh** [comment]
works perfectly now, thanks!
