### ISSUE TITLE
Suggest changing CONF_CODE to string

### ISSUE THREAD

**Issue by chadcb** [uvjustin/alarmdotcomajax#3]
Hello,

I have been testing various combinations of codes and notice anything with a leading zero fails due to the zero being stripped off. If conf code is changed to string, it works for codes with leading zeros. Here is what my updated  alarm_control_panel.py looks like:

`
#vol.Optional(CONF_CODE): cv.positive_int,
`
`
vol.Optional(CONF_CODE): cv.string,
`

For the configuration.yaml, if using leading zero, enclose in quotes:
`
code: "01234"
`

Thoughts?

**Comment by uvjustin** [comment]
I haven't used or tested the functionality of CONF_CODE at all - that part is left over from when I forked from the original HA alarmdotcom code. Your change makes sense..I'll go ahead and make the change. Let me know if you have any problems.
