### ISSUE TITLE
HACS integration

### ISSUE THREAD

**Issue by clsferguson** [uvjustin/alarmdotcomajax#6]
more of a request then an issue, can you integrate this with HACS? just for install and updating ease?

**Comment by uvjustin** [comment]
Just merged your PR. @aechelon previously said it was already on HACS, so I didn't think anything else was necessary. I haven't used HACS myself so not too sure how it works.
I can add the repository to the default repository list if that helps. Let me know.

**Comment by clsferguson** [comment]
Nope wasnt there. Needs the hacs.json. if you add it to the main list that would be helpful I'm sure. Lots of people will find it through hacs. The version number hacs populated for your repo is wrong though. Not sure where it gets that from. Probably in the hacs.json file too.

Thanks for making this.
