### ISSUE TITLE
Possible to clean up alarm states

### ISSUE THREAD

**Issue by pdobrien3** [uvjustin/alarmdotcomajax#8]
Love this custom component. Works awesome. Any chance the state of the alarm could be cleaned up?
disarmed to Disarmed
armed_home to Armed Home
armed_away to Armed Away. 

I tried to change this with a template sensor but then lose the ability to arm/disarm from the UI without some sort of yonky tap/hold action.

**Comment by uvjustin** [comment]
Not sure exactly what you are trying to do, but alarm states are constants that are defined in the HA core code base: https://github.com/home-assistant/core/blob/dev/homeassistant/const.py

**Comment by pdobrien3** [comment]
The entity alarm_control_panel.alarm_com has the following attributes:
1) when the alarm is disarmed, and you tap the entity in the UI, you are presented an option to arm home or arm away
2) the current states are disarmed, armed_home and armed_away

I would like the states to be Disarmed, Armed Home and Armed Away. When you use a template sensor to change the state, you lose #1 above because the template sensor is a sensor and not an alarm_control_panel. 

I realize since you created this custom component, you understand this far better than me.  If you know of a way through the sensor or customize.yaml to fix this I would be greatly appreciative. If not, I will head over the the home assistant github and see if it is something they are willing to look at. 

Thank you

**Comment by uvjustin** [comment]
I'm sorry I really don't understand the issue, maybe @aechelon can help?

**Comment by aechelon** [comment]
I think I understand the question.  
The states and their underlying values are not defined by the custom component.  They are defined at the Home Assistant level and imported by the component:

from homeassistant.const import (
    CONF_CODE,
    CONF_NAME,
    CONF_PASSWORD,
    CONF_USERNAME,
    STATE_ALARM_ARMED_AWAY,
    STATE_ALARM_ARMED_HOME,
    STATE_ALARM_DISARMED,
)

The behavior of the component is largely defined by the base class for all HA alarm control panels (alarm.AlarmControlPanel)

That said, you can customize a template sensor to reflect whatever string you want in the display.  
Here's an example I use in my configuration to convert the state string of my Nest to a string more suitable for display: 

```

  # List the current Nest Mode as "Home" or "Away"
  - platform: template
    sensors:
      nest_away_mode:
        friendly_name: "Nest Mode"
        value_template: >
          {% if is_state_attr('climate.bedroom_hallway', 'preset_mode', 'away') %}
            Away
          {% elif is_state_attr('climate.bedroom_hallway', 'preset_mode', 'Away and Eco') %}
            Away  
          {% else %}
            Home
          {% endif %} 

```

**Comment by pdobrien3** [comment]
@aechelon , thank you. Do you end up putting sensor.nest_away_mode in lovelace to see the results or can you keep the original nest entities?

**Comment by pdobrien3** [comment]
I upgraded to 0.109.4 today and the states are properly reporting again.  I guess it was just a bug during the over-haul of the frontend.  Thank you for your time and patience.

**Comment by uvjustin** [comment]
Glad that you got it sorted out
